language: java
script:
- mvn package
deploy:
  provider: releases
  file: "./target/*.jar"
  skip_cleanup: true
  draft: true
  api_key:
    secure: jWLZA81rfpeRjjkn66i/tLGbZVaL2imp4fiohKYh5SmD7C99wSM3ln+7Jc6v7x4Er/7r0utAJeR2OVoHFc7qmexcIlYB9aFNa+lMpbpnDrkLF9X2bH6/eKQlvfuEZUqUHiFcRbvCz0JGYsi1VIFJh20L0uQksGC6Uh716Hev0DgyekpHDBsqeLcWrULov00Z5j9yD5x1JRRVj0s5rmPpSk38T7eGJfPXmxwHn2qe7hKWzp8dsPJo3h1jy3hgDYzGcJYnwDoadDlYIgxcRsZ1fZtvH84K/z1GMG803yYl14Qw0vk6TdrMd5T7oTpnx9CEIibmIScN3TZJGmwDl3FnoocwN+LijDhvBbPq3vwSAsE4noWf6md1It+ijoW0g9V/jEJMl/ObcOcIV02RByX6WnjYsMwo4P8zpZaUBjaClWH9p7GO3Veyh6mIBPg1x9rvkBj4LGmb1IW/PoBmgSkKls818vj92nM0G2aK/c2lLExYhPcVXxuOsFooJvJChNbm3yglq/AK9sGBPNo5W5t6E9FVdEFDGsgYL7rN1HYBIjWyLQOHCZ1HL/zkv1HFmMr2WrwQWfLbGU/cjynR9jU0laaIYkPCtNZGWXrIj0mc46BpYUxwyM+EQGpojRD03LaS1CgpZm0017m6YziZOb67tkSXk9F17Q9jQvyu4BGJfUI=
  on:
   branch: main