language: java
os: windows
script:
  - mvn package
  - mvn javadoc:aggregate
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_OAUTH_TOKEN
    keep_history: true
    target_branch: gh-pages
    local_dir: ./target/site/apidocs
    on:
      branch: main
  - provider: releases
    file_glob: true
    file:
      - ./TextTransformerServer/target/*.jar
      - ./TextTransformerClient/target/*-jar-with-dependencies.jar
      - ./TextTransformerServer/user_dictionary.txt
    skip_cleanup: true
    api_key: $GITHUB_OAUTH_TOKEN
    on:
      branch: main
      tags: true

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
